# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'find.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Find(object):
    def setupUi(self, Find):
        Find.setObjectName("Find")
        Find.setWindowModality(QtCore.Qt.WindowModal)
        Find.resize(400, 128)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Find.sizePolicy().hasHeightForWidth())
        Find.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(Find)
        self.gridLayout.setObjectName("gridLayout")
        self.find_button = QtWidgets.QPushButton(Find)
        self.find_button.setObjectName("find_button")
        self.gridLayout.addWidget(self.find_button, 0, 2, 1, 1)
        self.cancel_button = QtWidgets.QPushButton(Find)
        self.cancel_button.setObjectName("cancel_button")
        self.gridLayout.addWidget(self.cancel_button, 2, 2, 1, 1)
        self.checks_and_radios_layout = QtWidgets.QHBoxLayout()
        self.checks_and_radios_layout.setObjectName("checks_and_radios_layout")
        self.checkbox_layout = QtWidgets.QVBoxLayout()
        self.checkbox_layout.setObjectName("checkbox_layout")
        self.match_case_checkbox = QtWidgets.QCheckBox(Find)
        self.match_case_checkbox.setObjectName("match_case_checkbox")
        self.checkbox_layout.addWidget(self.match_case_checkbox)
        self.wrap_around_checkbox = QtWidgets.QCheckBox(Find)
        self.wrap_around_checkbox.setObjectName("wrap_around_checkbox")
        self.checkbox_layout.addWidget(self.wrap_around_checkbox)
        self.checks_and_radios_layout.addLayout(self.checkbox_layout)
        self.find_direction = QtWidgets.QGroupBox(Find)
        self.find_direction.setObjectName("find_direction")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.find_direction)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.up_radio = QtWidgets.QRadioButton(self.find_direction)
        self.up_radio.setObjectName("up_radio")
        self.horizontalLayout_4.addWidget(self.up_radio)
        self.down_radio = QtWidgets.QRadioButton(self.find_direction)
        self.down_radio.setObjectName("down_radio")
        self.horizontalLayout_4.addWidget(self.down_radio)
        self.checks_and_radios_layout.addWidget(self.find_direction)
        self.gridLayout.addLayout(self.checks_and_radios_layout, 3, 0, 1, 1)
        self.find_text_layout = QtWidgets.QHBoxLayout()
        self.find_text_layout.setObjectName("find_text_layout")
        self.find_label = QtWidgets.QLabel(Find)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.find_label.sizePolicy().hasHeightForWidth())
        self.find_label.setSizePolicy(sizePolicy)
        self.find_label.setObjectName("find_label")
        self.find_text_layout.addWidget(self.find_label)
        self.find_line_edit = QtWidgets.QLineEdit(Find)
        self.find_line_edit.setObjectName("find_line_edit")
        self.find_text_layout.addWidget(self.find_line_edit)
        self.gridLayout.addLayout(self.find_text_layout, 0, 0, 1, 1)

        self.retranslateUi(Find)
        QtCore.QMetaObject.connectSlotsByName(Find)

    def retranslateUi(self, Find):
        _translate = QtCore.QCoreApplication.translate
        Find.setWindowTitle(_translate("Find", "Find…"))
        self.find_button.setText(_translate("Find", "Find next"))
        self.cancel_button.setText(_translate("Find", "Cancel"))
        self.match_case_checkbox.setText(_translate("Find", "Match case"))
        self.wrap_around_checkbox.setText(_translate("Find", "Wrap around"))
        self.find_direction.setTitle(_translate("Find", "Direction"))
        self.up_radio.setText(_translate("Find", "Up"))
        self.down_radio.setText(_translate("Find", "Down"))
        self.find_label.setText(_translate("Find", "Find:"))
